# 00. PyTorch Fundamentals

Based on: https://www.learnpytorch.io/00_pytorch_fundamentals/

In [1]:
import torch
print("Hello, we are running pytorch version: %s" % torch.__version__)

Hello, we are running pytorch version: 2.1.2


## Tensors

### Creating a tensor

PyTorch tensors are created using `torch.tensor()` (https://pytorch.org/docs/stable/tensors.html)

In [2]:
# Scalar 
scalar = torch.tensor(11)
scalar

tensor(11)

In [3]:
#Get dimension of tensor, scalars are of dimension 0
scalar.ndim

0

In [4]:
#Get tensor back as python int
scalar.item()

11

In [5]:
# Vector
vec = torch.tensor([11,11])
vec

tensor([11, 11])

In [6]:
vec.ndim

1

In [7]:
vec.shape

torch.Size([2])

In [8]:
# MATRIX
MATRIX = torch.tensor([[11,12],
                       [13,14]])
MATRIX

tensor([[11, 12],
        [13, 14]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX.shape

torch.Size([2, 2])

In [11]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3,5],[3,6,9,2],[2,4,6,66]],[[2,4,6,100],[7,8,9,200],[10,11,23,300]]])
TENSOR

tensor([[[  1,   2,   3,   5],
         [  3,   6,   9,   2],
         [  2,   4,   6,  66]],

        [[  2,   4,   6, 100],
         [  7,   8,   9, 200],
         [ 10,  11,  23, 300]]])

In [12]:
TENSOR.ndim

3

In [13]:
TENSOR.shape

torch.Size([2, 3, 4])

In [14]:
TENSOR[0]

tensor([[ 1,  2,  3,  5],
        [ 3,  6,  9,  2],
        [ 2,  4,  6, 66]])

### Random tensors

Why? Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

In [15]:
# Create a random tensor of shape (3, 4)
random_tensor = torch.rand(3, 3)

In [16]:
random_tensor

tensor([[0.1610, 0.8996, 0.8611],
        [0.3245, 0.6322, 0.5401],
        [0.1471, 0.6450, 0.9608]])

In [17]:
random_tensor.ndim

2

In [18]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(64,64,3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([64, 64, 3]), 3)

### Zeros and Ones

In [19]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3,3))
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [20]:
zeros * random_tensor

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

### Create a tensor of all ones

In [21]:
ones = torch.ones(size=(3,3))
ones

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [22]:
ones.dtype

torch.float32

In [23]:
one_to_ten = torch.arange(1,11)
zero_to_thousand = torch.arange(start=0, end=1000, step=66)

In [24]:
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [25]:
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [26]:
float_32_tensor = torch.tensor(
    [3.0, 6.0, 9.0],
    dtype=None,
    device=None,
    requires_grad=False
)

In [27]:
float_32_tensor.dtype

torch.float32

In [28]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [29]:
float_32_tensor * float_16_tensor

tensor([ 9., 36., 81.])

In [30]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [31]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

In [32]:
float_32_tensor.dtype,float_32_tensor.shape,float_32_tensor.device

(torch.float32, torch.Size([3]), device(type='cpu'))

In [33]:
some_random_tensor = torch.rand(3,4)

In [34]:
print(some_random_tensor)
print(f"Datatype of tensor: {some_random_tensor.dtype}")
print(f"Shape of tensor: {some_random_tensor.shape}")
print(f"Device of tensor: {some_random_tensor.device}")

tensor([[0.3986, 0.3315, 0.0854, 0.9462],
        [0.3913, 0.9404, 0.7527, 0.9935],
        [0.8413, 0.6024, 0.5184, 0.0447]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device of tensor: cpu


### Manipulating Tensor
Operations include:
 - Addition
 - Subtraction
 - Multiplication (element-wise)
 - Division
 - Matrix multiplication

In [35]:
# Create a tensor and add 10 to it
my_tensor = torch.tensor([1,2,3])
my_tensor + 10

tensor([11, 12, 13])

In [36]:
# Multiply tensor by 10
my_tensor * 10

tensor([10, 20, 30])

In [37]:
my_tensor

tensor([1, 2, 3])

In [38]:
# Subtract 10
my_tensor - 10

tensor([-9, -8, -7])

In [39]:
# Try out PyTorch in-built functions
torch.mul(my_tensor, 10)

tensor([10, 20, 30])

In [40]:
torch.add(my_tensor, 10)

tensor([11, 12, 13])

### Matrix multiplication

Two main ways in deep learning
1. Elements wise
2. Dot product

For matrix multiplication:
1. Inner dimensions must match:
* `(3,2) @ (3,2)` won't work
* `(2,3) @ (3,2)` works
  
2. The resulting matrix has the spae of the outer dimensions

In [41]:
mat_mul_tensor1 = torch.randn(3,2)
mat_mul_tensor2 = torch.randn(2,3)

In [42]:
torch.matmul(mat_mul_tensor1, mat_mul_tensor2)

tensor([[ 1.2859, -0.6357, -0.3124],
        [-4.0379,  2.3191, -0.1012],
        [-0.2691,  0.0042,  0.4973]])

### One of the most common errors in deep learning is shape errors

In [43]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])

tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])
tensor_A @ tensor_B.T

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

## Finding min, max, mean, sum, etc (tensor aggregation)

In [44]:
# Create a tensor
x = torch.arange(0,100,10)
x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [45]:
# Find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [46]:
# Find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [47]:
# Find the mean
torch.mean(x,dtype=torch.float32), x.mean(dtype=torch.float32)

(tensor(45.), tensor(45.))

In [48]:
# Find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

In [49]:
# Find the positional min and max
print(f"Minimum position: {x.argmin()}")
print(f"Maximum position: {x.argmax()}")

Minimum position: 0
Maximum position: 9
