# Indexing (selecting data from tensors)
Indexing with PyTorch is similar to indexing with NumPy

In [2]:
import torch

In [3]:
# Create a tensor
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [4]:
# How to index
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [5]:
x[0][0]

tensor([1, 2, 3])

In [6]:
x[0,0]

tensor([1, 2, 3])

In [8]:
x[0,0,2]

tensor(3)

In [9]:
x[0,:,2]

tensor([3, 6, 9])

In [11]:
x[0,2,2]

tensor(9)

In [12]:
x[0,0,:]

tensor([1, 2, 3])

In [13]:
x[0,:,:]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])