# PyTorch tensors & NumPy

In [1]:
import torch
import numpy as np

In [3]:
# NumPy to PyTorch tensor
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array) # Becomes float64 because numpy uses float64
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [4]:
# Change the value of array, what will happen to tensor
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [6]:
# PyTorch tensor to NumPy
tensor = torch.ones(7)
numpy_tensor = tensor.numpy() # Becomes float32 because PyTorch uses float32
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [7]:
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

Tensor and Numpyarray don't share memory