## Reproducibility


In [1]:
import torch

In [2]:
RANDOM_SEED = 42

In [3]:
torch.manual_seed(RANDOM_SEED)
rand_tensor_a = torch.rand(3,4)
torch.manual_seed(RANDOM_SEED)
rand_tensor_b = torch.rand(3,4)

print(f"A:\n {rand_tensor_a}")
print(f"B:\n {rand_tensor_b}")
print(f"Equality:\n {rand_tensor_a == rand_tensor_b}")

A:
 tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
B:
 tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
Equality:
 tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])
