In [1]:
import torch

In [2]:
torch.__version__

'2.1.2'

In [3]:
tensor = torch.rand(7,7)
tensor.shape

torch.Size([7, 7])

In [4]:
another_tensor = torch.rand(1,7)

In [5]:
tensor.shape, another_tensor.T.shape

(torch.Size([7, 7]), torch.Size([7, 1]))

In [6]:
mat_mul_result = torch.mm(tensor,another_tensor.T)

In [7]:
mat_mul_result

tensor([[1.7526],
        [2.0169],
        [1.7115],
        [1.7249],
        [2.5175],
        [1.9493],
        [1.7530]])

In [8]:
tensor, another_tensor

(tensor([[0.0232, 0.6992, 0.3651, 0.5589, 0.4195, 0.2001, 0.6877],
         [0.4964, 0.3911, 0.9829, 0.6458, 0.8018, 0.2201, 0.4243],
         [0.1719, 0.7228, 0.4304, 0.4801, 0.0621, 0.0311, 0.9049],
         [0.9106, 0.4745, 0.7718, 0.3116, 0.0757, 0.0506, 0.4832],
         [0.6663, 0.9052, 0.4592, 0.1874, 0.0878, 0.7330, 0.5835],
         [0.6742, 0.5206, 0.1472, 0.1373, 0.8099, 0.3158, 0.5517],
         [0.2246, 0.1341, 0.8028, 0.4842, 0.5262, 0.8345, 0.1789]]),
 tensor([[0.4813, 0.9881, 0.5125, 0.0477, 0.4770, 0.8451, 0.6800]]))

In [9]:
RANDOM_SEED = 0
torch.manual_seed(RANDOM_SEED)
a = torch.rand(7,7)
b = torch.rand(1,7)
a,b

(tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
         [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
         [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
         [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
         [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
         [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
         [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]]),
 tensor([[0.4820, 0.8198, 0.9971, 0.6984, 0.5675, 0.8352, 0.2056]]))

In [10]:
torch.backends.mps.is_available()

True

In [11]:
torch.cuda.is_available()

False

In [13]:
torch.mps.manual_seed(RANDOM_SEED)

In [15]:
torch.manual_seed(1234)
a = torch.rand(2,3)
b = torch.rand(2,3)

In [23]:
a.device, b.device

(device(type='mps', index=0), device(type='mps', index=0))

In [21]:
a = a.to('mps')

In [22]:
b = b.to('mps')

In [25]:
a_times_b =  a @ b.T

In [26]:
a_times_b

tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]], device='mps:0')

In [29]:
a_times_b.max(), a_times_b.min()

(tensor(0.5617, device='mps:0'), tensor(0.3647, device='mps:0'))

In [30]:
torch.max(a_times_b), torch.min(a_times_b)

(tensor(0.5617, device='mps:0'), tensor(0.3647, device='mps:0'))

In [31]:
torch.argmax(a_times_b), torch.argmin(a_times_b)

(tensor(3, device='mps:0'), tensor(0, device='mps:0'))

In [40]:
random_tensor = torch.rand(1,3,1,10)
random_tensor.shape

torch.Size([1, 3, 1, 10])

In [47]:
squeezed = torch.squeeze(random_tensor, dim=1)
squeezed

tensor([[[[0.6839, 0.7658, 0.9149, 0.3993, 0.1100, 0.2541, 0.4333, 0.4451,
           0.4966, 0.7865]],

         [[0.6604, 0.1303, 0.3498, 0.3824, 0.8043, 0.3186, 0.2908, 0.4196,
           0.3728, 0.3769]],

         [[0.0108, 0.9455, 0.7661, 0.2634, 0.1880, 0.5174, 0.7849, 0.1412,
           0.3112, 0.7091]]]])

In [39]:
squeezed.shape

torch.Size([3, 10])

In [36]:
random_tensor.shape

torch.Size([1, 1, 1, 10])