In [1]:
import sklearn
from sklearn.datasets import make_circles
import pandas as pd
from matplotlib import pyplot as plt
import torch

In [2]:
N_SAMPLES = 1000

In [10]:
torch.__version__

'2.1.2'

In [3]:
X, y = make_circles(N_SAMPLES, noise=0.03, random_state=42)

In [4]:
len(X),len(y)

(1000, 1000)

In [5]:
print(f"First 5 samples of X: \n {X[:5]}")
print(f"First 5 samples of Y: \n {y[:5]}") 

First 5 samples of X: 
 [[ 0.75424625  0.23148074]
 [-0.75615888  0.15325888]
 [-0.81539193  0.17328203]
 [-0.39373073  0.69288277]
 [ 0.44220765 -0.89672343]]
First 5 samples of Y: 
 [1 1 1 1 0]


In [7]:
circles = pd.DataFrame({"X1": X[:,0],
                        "X2": X[:,1],
                        "Label": y})
circles.head(10)

X1        X2  Label
0  0.754246  0.231481      1
1 -0.756159  0.153259      1
2 -0.815392  0.173282      1
3 -0.393731  0.692883      1
4  0.442208 -0.896723      0
5 -0.479646  0.676435      1
6 -0.013648  0.803349      1
7  0.771513  0.147760      1
8 -0.169322 -0.793456      1
9 -0.121486  1.021509      0

In [ ]:
plt.scatter(x=X[:,0], y=X[:,1], c=y, cmap=plt.cm.RdYlBu)

## Check input and output shapes

In [8]:
X.shape, y.shape

((1000, 2), (1000,))

In [9]:
X_sample = X[0]
y_sample = y[0]

print(f"Values of X: {X_sample} and Y: {y_sample}")
print(f"Shapes of X: {X_sample.shape} and Y: {y_sample.shape}")

Values of X: [0.75424625 0.23148074] and Y: 1
Shapes of X: (2,) and Y: ()


## Convert into Tensors

In [11]:
X = torch.from_numpy(X).type(torch.float)
y = torch.from_numpy(y).type(torch.float)

In [12]:
X[:5], y[:5]

(tensor([[ 0.7542,  0.2315],
         [-0.7562,  0.1533],
         [-0.8154,  0.1733],
         [-0.3937,  0.6929],
         [ 0.4422, -0.8967]]),
 tensor([1., 1., 1., 1., 0.]))

In [13]:
X.dtype, y.dtype

(torch.float32, torch.float32)